export type PropertyType = string
export type HostedProperty = Record<string, unknown>
export type HostDashboardStats = Record<string, unknown>
export type HostTaskProps = Record<string, unknown>
export type MiniMetricProps = Record<string, unknown>
export type PropertyCardProps = Record<string, unknown>
export type QuickActionProps = Record<string, unknown>
export type HostBooking = Record<string, unknown>
export type HostBookingActionProps = Record<string, unknown>
